# Generated by Django 5.1.4 on 2025-05-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_orderitem_product_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_id',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
