# Generated by Django 5.1.4 on 2025-05-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_chat_id_profile_telegram_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
